server:
  port: 8010

spring:
  application:
    name: movie-eureka

user:
  userServiceUrl: http://localhost:8000/

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
