server:
  port: 8000

spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2 # 指定数据源类型
    schema: classpath:schema.sql # 指定h2数据库的建表脚本
    data: classpath:data.sql # 指定h2数据库的数据脚本
    username: root
    password: root
    url: jdbc:h2:mem:cib
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console


logging:
  level: DEBUG
  org.hibernate: DEBUG
  org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  org.hibernate.type.descriptor.sql.BasicExtractor: TRACE