server:
  port: 8000

spring:
  application:
    name: user-eureka
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2 # 指定数据源类型
    schema: classpath:schema.sql # 指定h2数据库的建表脚本
    data: classpath:data.sql # 指定h2数据库的数据脚本
    username: root
    password: root
    url: jdbc:h2:mem:cib
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true

logging:
  level:
    root: debug

